In [54]:
import numpy
np.set_printoptions(precision=8, suppress=True)

In [55]:
# one step func
def T_inv(m):
    m_inv = np.zeros((4, 4))
    m_inv[:3, :3] = m[:3, :3].T
    m_inv[:3, 3] = np.dot(-m[:3, :3].T ,m[:3, 3])
    m_inv[3, 3] = 1
    
    return m_inv

In [64]:
m = [[0.0013861226083627316,  0.9999877848380936,     0.004744348081373055,  -0.006740962728286615],
     [0.9999983768131799,    -0.001391567327544259,   0.0011445135989464673,  0.0030275147117085487],
     [0.0011511016983080883,  0.0047427539442347014, -0.9999880905540347,    -0.001127656409883309],
     [0.0, 0.0, 0.0, 1.0]]

cam0 = [[0.018838379228253904, -0.9998206730555423, 0.0019331835954350396, 0.0015057845240342754],
        [-0.0011499189320001713, -0.0019551918497311416, -0.9999974274523307, 0.007756314231201401],
        [0.9998218807140105, 0.018836107761209864, -0.0011865453660810377, -0.049890705309496935],
        [0.0, 0.0, 0.0, 1.0]]



cam1 = [[0.019318485824922654, -0.9998118341848503, 0.0017585020209882618, -0.04836218672492272],
        [-0.0009044232386054563, -0.001776304854874844, -0.9999980133778609, 0.007903278603917525],
        [0.9998129715722026, 0.01931685701629815, -0.0009385685772290708, -0.049562251185862376],
        [0.0, 0.0, 0.0, 1.0]]

In [60]:
A = np.array(m)
A


array([[ 0.00138612,  0.99998778,  0.00474435, -0.00674096],
       [ 0.99999838, -0.00139157,  0.00114451,  0.00302751],
       [ 0.0011511 ,  0.00474275, -0.99998809, -0.00112766],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [66]:
cam0_m = np.array(cam0)
cam1_m = np.array(cam1)

print(cam0_m)
print('\n\n\n')
print(cam1_m)

[[ 0.01883838 -0.99982067  0.00193318  0.00150578]
 [-0.00114992 -0.00195519 -0.99999743  0.00775631]
 [ 0.99982188  0.01883611 -0.00118655 -0.04989071]
 [ 0.          0.          0.          1.        ]]




[[ 0.01931849 -0.99981183  0.0017585  -0.04836219]
 [-0.00090442 -0.0017763  -0.99999801  0.00790328]
 [ 0.99981297  0.01931686 -0.00093857 -0.04956225]
 [ 0.          0.          0.          1.        ]]


In [67]:
cam0_inv = T_inv(cam0_m)
cam1_inv = T_inv(cam1_m)

print(cam0_inv)
print('\n\n\n')
print(cam1_inv)

[[ 0.01883838 -0.00114992  0.99982188  0.04986237]
 [-0.99982067 -0.00195519  0.01883611  0.00246043]
 [ 0.00193318 -0.99999743 -0.00118655  0.00769419]
 [ 0.          0.          0.          1.        ]]




[[ 0.01931849 -0.00090442  0.99981297  0.05049441]
 [-0.99981183 -0.0017763   0.01931686 -0.04738166]
 [ 0.0017585  -0.99999801 -0.00093857  0.00794179]
 [ 0.          0.          0.          1.        ]]


In [61]:
T_inv(A)

array([[ 0.00138612,  0.99999838,  0.0011511 , -0.00301687],
       [ 0.99998778, -0.00139157,  0.00474275,  0.00675044],
       [ 0.00474435,  0.00114451, -0.99998809, -0.00109913],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [38]:
import numpy as np
np.set_printoptions(precision=8, suppress=True)
A = np.array([[0.00128876, 0.99999914, -0.00023326, -0.00323207],
              [0.99999859, -0.00128851, 0.00107949, -0.06857642],
              [0.00107919, -0.00023466, -0.99999939, -0.00014712],
              [0, 0, 0, 1]])



In [45]:
A[:3, :3]

array([[ 0.00128876,  0.99999859,  0.00107919],
       [ 0.99999914, -0.00128851, -0.00023466],
       [-0.00023326,  0.00107949, -0.99999939]])

In [46]:
A[:3, 3]

array([ 0.06858065,  0.00314367, -0.00007385])

In [47]:
R_inv = np.zeros((4, 4))
R_inv

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
R_inv[:3, :3] = A[:3, :3].T
print(R_inv)

[[ 0.00128876  0.99999914 -0.00023326  0.        ]
 [ 0.99999859 -0.00128851  0.00107949  0.        ]
 [ 0.00107919 -0.00023466 -0.99999939  0.        ]
 [ 0.          0.          0.          0.        ]]


In [49]:
R_inv[:3, 3] = np.dot(-A[:3, :3].T ,A[:3, 3])
print(R_inv)

[[ 0.00128876  0.99999914 -0.00023326 -0.00323207]
 [ 0.99999859 -0.00128851  0.00107949 -0.06857642]
 [ 0.00107919 -0.00023466 -0.99999939 -0.00014712]
 [ 0.          0.          0.          0.        ]]


In [50]:
R_inv[3, 3] = 1
print(R_inv)

[[ 0.00128876  0.99999914 -0.00023326 -0.00323207]
 [ 0.99999859 -0.00128851  0.00107949 -0.06857642]
 [ 0.00107919 -0.00023466 -0.99999939 -0.00014712]
 [ 0.          0.          0.          1.        ]]


In [51]:


# one step func
def T_inv(m):
    m_inv = np.zeros((4, 4))
    m_inv[:3, :3] = m[:3, :3].T
    m_inv[:3, 3] = np.dot(-m[:3, :3].T ,m[:3, 3])
    m_inv[3, 3] = 1
    
    return m_inv