In [5]:
import numpy as np


def Train(X,Y,lr,epochs):
    # 初始化权重矩阵
    W1 = np.ones((3,4))
    W2 = np.ones((2,3))
    W3 = np.ones((1,2))
    
    
    for i in range(epochs):
        # 正向传播
        h = np.dot(W1,X)    # 第一层
        k = np.dot(W2,h)    # 第二层
        y = np.dot(W3,k)
        # 求loss
        loss = np.sum((Y-y)**2)/2
        # 求误差项
        S3 = y-Y
        S2 = np.dot(W3.T, S3)
        S1 = np.dot(W2.T, S2)
        
        # 求偏导
        dW1 = np.dot(S1, X.T)
        dW2 = np.dot(S2, h.T)
        dW3 = np.dot(S3, k.T)
        # 更新w
        W1 = W1 - lr*dW1
        W2 = W2 - lr*dW2
        W3 = W3 - lr*dW3
        
    return W1,W2,W3,loss



# 创建数据
X = np.array([[1],
              [2],
              [3],
              [4]
                ])

Y = np.array([[100],
              ])

# 训练
W1, W2, W3, loss= Train(X,Y,0.0001, 500)
print(W1)
print('\n')
print(W2)
print('\n')
print(W3)
print('\n')
print(loss)
print('\n')
# 预测(其实就相当于进行一次正向传播)
h = np.dot(W1,X)
k = np.dot(W2,h)
y = np.dot(W3,k)
print(y)

[[1.02680555 1.05361109 1.08041664 1.10722218]
 [1.02680555 1.05361109 1.08041664 1.10722218]
 [1.02680555 1.05361109 1.08041664 1.10722218]]


[[1.13146258 1.13146258 1.13146258]
 [1.13146258 1.13146258 1.13146258]]


[[1.36338117 1.36338117]]


4.0389678347315804e-28


[[100.]]


In [7]:
k

array([[36.67352971],
       [36.67352971]])

In [3]:
import numpy as np

batch = 100

#创建数据集
X = np.random.randn(4, batch)
Y = np.sum(X,axis=0)+10
print(X[:,None,0].shape)



def Train(X,Y,lr,epochs):
    # 初始化权重矩阵
    W1 = np.random.randn(3,4)
    W2 = np.random.randn(2,3)
    W3 = np.random.randn(1,2)
    
    
    for i in range(epochs):
        for j in range(batch):
            # 正向传播
            tx = X[:,None,j]
            h = np.dot(W1,tx)    # 第一层
            h_relu = np.max(h, 0)
            k = np.dot(W2,h_relu)    # 第二层
            k_relu = np.max(k, 0)
            y = np.dot(W3,k_relu)
            # 求loss
            loss = np.sum((Y[j]-y)**2)/2
            # 求误差项
            S3 = y-Y[j]
            S2_relu = (S3 > 0) * S3
            S2 = np.dot(W3.T, S3)
            S1 = np.dot(W2.T, S2)

            # 求偏导
            dW1 = np.dot(S1, tx.T)
            dW2 = np.dot(S2, h.T)
            dW3 = np.dot(S3, k.T)
            # 更新w
            W1 = W1 - lr*dW1
            W2 = W2 - lr*dW2
            W3 = W3 - lr*dW3
        
    return W1,W2,W3,loss

# 训练
W1, W2, W3, loss= Train(X,Y,0.0001, 10)
print(W1)
print('\n')
print(W2)
print('\n')
print(W3)
print('\n')
print(loss)
print('\n')



(4, 1)


ValueError: shapes (2,3) and (1,) not aligned: 3 (dim 1) != 1 (dim 0)

In [62]:
# 预测(其实就相当于进行一次正向传播)
h = np.dot(W1,[[1],[2],[3],[4]])
k = np.dot(W2,h)
y = np.dot(W3,k)
print(y)

[[10.22479294]]


In [51]:
Y[0]

1.6944300965938406

In [11]:
X = np.random.randn(4, 1000)
X.shape

(4, 1000)

In [14]:
np.sum(X,axis=0).shape

(1000,)

In [44]:
X = np.random.randn(4, 100)
Y = np.sum(X,axis=0)

a = X[:,None,0].shape
a

(4, 1)

In [40]:

(a[0,0] + a[1,0] + a[2,0] + a[3,0])

2.9262022659207894

In [41]:
Y[0]

2.9262022659207894

In [77]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [80]:
X1

array([[1],
       [1],
       [1]])

In [81]:
X2

array([[5, 2, 3, 4]])

In [8]:
import torch
flag = torch.cuda.is_available()
print(flag)

True


In [9]:
device = torch.device("cuda:0")
print(device)
print(torch.cuda.get_device_name(0))
print(torch.rand(3,3).cuda()) 


cuda:0
NVIDIA GeForce RTX 3060 Laptop GPU
tensor([[0.3986, 0.7106, 0.1637],
        [0.4705, 0.1767, 0.3417],
        [0.1905, 0.7323, 0.1180]], device='cuda:0')
